sudo: required

services:
  - docker

cache:
  directories:
    - repo/


before_install:
  - openssl aes-256-cbc -K $encrypted_24bb3a5ef758_key -iv $encrypted_24bb3a5ef758_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
  - tar xvfz secrets.tar.gz
  - chmod 600 deploy_key
  - docker build --build-arg USER_ID="$(id -u)" -t "$DOCKER_TAG" docker/

script:
  - docker run -e REPO_NAME="$REPO_NAME" -v="$PWD":/home/builder/aur-build "$DOCKER_TAG"

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only: master

env:
  global:
    - PUSH_BRANCH=gh-pages
    - DOCKER_TAG=aur-build
    - REPO_NAME=build
